# Built with Jekyll 3.2.0

# Setup
title:               Shelley
tagline:             'Love's Philosophy'
description:         'The poem Windom Earle sends Shelly, Audrey, and Donna
url:                 'http://danielarobinson.github.io'
baseurl:             '/Shelley'

# About/contact
author:
  name:              Alex Gil
  url:               https://twitter.com/DRobinsonMDP
  email:             danielrobinsonmail@gmail.com

# Permalinks

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Custom vars
version:             0.0.6

# Exclusions from the final site
exclude: [optional, vendor]


